apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useWorkloadIdentity: "true"
    clientID: "WORKLOAD_IDENTITY_CLIENT_ID_PLACEHOLDER"
    keyvaultName: "ola-kv-dev"
    tenantId: "5ee10fdc-b731-4ee9-9181-0dad7378a345"
    objects: |
      array:
        - |
          objectName: acr-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: acr-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: sonar-token
          objectType: secret
          objectVersion: ""
    # Optional: filter secrets by tags
    # objectTypes: secret
    # filterTags: |
    #   environment: production

