apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "1e17b78e-822b-486e-ba6b-2da0d93c4d82"
    azure.workload.identity/use: "true"

