sonar.projectKey=OlatunbosunIbiyinka_Olatunbosun-portfolio-project
sonar.organization=olatunbosunibiyinka
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**
