groups:
- name: portfolio-app-alerts
  rules:
  - alert: HighCpuUsage
    expr: sum(rate(container_cpu_usage_seconds_total{pod=~"ola-portfolio-app.*"}[2m])) > 0.8
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on portfolio-app pod"
      description: "Pod {{ $labels.pod }} CPU usage is above 80%"
