apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-email-alert
  namespace: monitoring
spec:
  groups:
  - name: test-alert
    rules:
    - alert: TestEmailAlert
      expr: vector(1)
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Test Email Alert"
        description: "This is a test alert to verify Grafana SMTP notifications."
