alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

    # This is required to make the secret available inside the pod
    secrets:
      - alertmanager-smtp-secret

    # Mount the secret to the correct path for __file{}
    extraVolumeMounts:
      - name: alertmanager-smtp-secret
        mountPath: /etc/alertmanager/smtp/password
        subPath: password
        readOnly: true

    extraVolumes:
      - name: alertmanager-smtp-secret
        secret:
          secretName: alertmanager-smtp-secret

    config:
      global:
        smtp_smarthost: 'smtp.gmail.com:587'
        smtp_from: 'olatunbosunkayode47@gmail.com'
        smtp_auth_username: 'olatunbosunkayode47@gmail.com'
        smtp_auth_password: '__file{/etc/alertmanager/smtp/password}'
        smtp_require_tls: true
      route:
        receiver: 'email-notifications'
        group_by:
          - namespace
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
      receivers:
        - name: 'email-notifications'
          email_configs:
            - to: 'olatunbosunkayode47@gmail.com'
              send_resolved: true

additionalPrometheusRules:
  - name: portfolio-app-alerts
    groups:
      - name: portfolio-app-alerts
        rules:
          - alert: HighCpuUsage
            expr: sum(rate(container_cpu_usage_seconds_total{pod=~"ola-portfolio-app.*"}[2m])) > 0.8
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on portfolio-app pod"
              description: "Pod {{ $labels.pod }} CPU usage is above 80%"
          - alert: PodRestartHigh
            expr: increase(kube_pod_container_status_restarts_total{pod=~"ola-portfolio-app.*"}[5m]) > 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Portfolio app pod restarting"
              description: "Pod {{ $labels.pod }} has restarted more than once in the last 5 minutes"

grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: olatunbosunkayode47@gmail.com
      password: $__file{/etc/secrets/grafana-smtp/password}
      skip_verify: true
      from_address: olatunbosunkayode47@gmail.com
      from_name: "Grafana Alerts"

  extraSecretMounts:
    - name: grafana-smtp-secret
      secretName: grafana-smtp-secret
      mountPath: /etc/secrets/grafana-smtp
      defaultMode: 0440
      readOnly: true
